packages:
  - apps/*
  - packages/*

allowBuilds:
  '@astryxdesign/cli': false
  '@astryxdesign/core': false
  '@parcel/watcher': true
  esbuild: true
  rome: set this to true or false
  sharp: true

onlyBuiltDependencies:
  - sharp
