-- Your SQL goes here
ALTER TABLE channels RENAME TO feeds;
ALTER TABLE feeds ADD COLUMN feed_type VARCHAR NOT NULL DEFAULT "";
ALTER TABLE feeds ADD COLUMN updated DATETIME;
UPDATE feeds SET updated = CURRENT_TIMESTAMP;
ALTER TABLE feeds ADD COLUMN logo TEXT NOT NULL DEFAULT "";
