export const SYNC_UNREAD_WHEN_APP_START = 'SYNC_UNREAD_WHEN_APP_START';
export const FINISH_INITIAL_SYNC = 'FINISH_INITIAL_SYNC';
export const MANUAL_SYNC_UNREAD = 'MANUAL_SYNC_UNREAD';
export const FINISH_MANUAL_SYNC_UNREAD = 'FINISH_MANUAL_SYNC_UNREAD';
export const UPDATE_WINDOW_ID = 'UPDATE_WINDOW_ID';
