export const SYNC_UNREAD_WHEN_START = 'SYNC_UNREAD_WHEN_START';
export const FINISH_INITIAL_SYNC = 'FINISH_INITIAL_SYNC';
export const SYNC_UNREAD = 'SYNC_UNREAD';
export const UPDATE_WINDOW_ID = 'UPDATE_WINDOW_ID';
