/**
 * Do not edit directly
 * Generated on Sat, 06 May 2023 08:36:34 GMT
 */

export const ColorPalette6Section1ElementsBackground : string;
export const ColorPalette6Section1ElementsHeadline : string;
export const ColorPalette6Section1ElementsParagraph : string;
export const ColorPalette6Section1ElementsButton : string;
export const ColorPalette6Section1ElementsButtonText : string;
export const ColorPalette6Section1IllustrationStroke : string;
export const ColorPalette6Section1IllustrationMain : string;
export const ColorPalette6Section1IllustrationHighlight : string;
export const ColorPalette6Section1IllustrationSecondary : string;
export const ColorPalette6Section1IllustrationTertiary : string;
export const ColorPalette6Section2ElementsBackground : string;
export const ColorPalette6Section2ElementsHeadline : string;
export const ColorPalette6Section2ElementsSubHeadline : string;
export const ColorPalette6Section2ElementsCardBackground : string;
export const ColorPalette6Section2ElementsCardHeading : string;
export const ColorPalette6Section2ElementsCardParagraph : string;
export const ColorPalette6Section2IconsStroke : string;
export const ColorPalette6Section2IconsMain : string;
export const ColorPalette6Section2IconsHighlight : string;
export const ColorPalette6Section2IconsSecondary : string;
export const ColorPalette6Section2IconsTertiary : string;
export const ColorPalette6Section3Background : string;
export const ColorPalette6Section3Headline : string;
export const ColorPalette6Section3Paragraph : string;
export const ColorPalette6Section3CardBackground : string;
export const ColorPalette6Section3CardHeadline : string;
export const ColorPalette6Section3CardParagraph : string;
export const ColorPalette6Section3CardTagBackground : string;
export const ColorPalette6Section3CardTagText : string;
export const ColorPalette6Section3CardHighlight : string;
export const ColorPalette6Section4ElementsBackground : string;
export const ColorPalette6Section4ElementsHeadline : string;
export const ColorPalette6Section4ElementsParagraph : string;
export const ColorPalette6Section4ElementsLink : string;
export const ColorPalette6Section4ElementsCardBackgroud : string;
export const ColorPalette6Section4ElementsCardHeadline : string;
export const ColorPalette6Section4ElementsCardParagraph : string;
export const ColorPalette6Section4NewsletterBackground : string;
export const ColorPalette6Section4NewsletterFormInput : string;
export const ColorPalette6Section4NewsletterLabelPlaceholder : string;
export const ColorPalette6Section4NewsletterFormButton : string;
export const ColorPalette6Section4NewsletterFormButtonText : string;
export const ColorPalette6Section5ElementsBackground : string;
export const ColorPalette6Section5ElementsHeadline : string;
export const ColorPalette6Section5ElementsParagraph : string;
export const ColorPalette6Section5ElementsLinks : string;
