/**
 * Do not edit directly
 * Generated on Sat, 06 May 2023 08:36:34 GMT
 */

export const ColorPalette7Section1ElementsBackground : string;
export const ColorPalette7Section1ElementsHeadline : string;
export const ColorPalette7Section1ElementsParagraph : string;
export const ColorPalette7Section1ElementsButton : string;
export const ColorPalette7Section1ElementsButtonText : string;
export const ColorPalette7Section1IllustrationStroke : string;
export const ColorPalette7Section1IllustrationMain : string;
export const ColorPalette7Section1IllustrationHighlight : string;
export const ColorPalette7Section1IllustrationSecondary : string;
export const ColorPalette7Section1IllustrationTertiary : string;
export const ColorPalette7Section2ElementsBackground : string;
export const ColorPalette7Section2ElementsHeadline : string;
export const ColorPalette7Section2ElementsSubHeadline : string;
export const ColorPalette7Section2ElementsCardBackground : string;
export const ColorPalette7Section2ElementsCardHeading : string;
export const ColorPalette7Section2ElementsCardParagraph : string;
export const ColorPalette7Section2IconsStroke : string;
export const ColorPalette7Section2IconsMain : string;
export const ColorPalette7Section2IconsHighlight : string;
export const ColorPalette7Section2IconsSecondary : string;
export const ColorPalette7Section2IconsTertiary : string;
export const ColorPalette7Section3Background : string;
export const ColorPalette7Section3Headline : string;
export const ColorPalette7Section3Paragraph : string;
export const ColorPalette7Section3CardBackground : string;
export const ColorPalette7Section3CardHeadline : string;
export const ColorPalette7Section3CardParagraph : string;
export const ColorPalette7Section3CardTagBackground : string;
export const ColorPalette7Section3CardTagText : string;
export const ColorPalette7Section3CardHighlight : string;
export const ColorPalette7Section4ElementsBackground : string;
export const ColorPalette7Section4ElementsHeadline : string;
export const ColorPalette7Section4ElementsParagraph : string;
export const ColorPalette7Section4ElementsLink : string;
export const ColorPalette7Section4ElementsCardBackgroud : string;
export const ColorPalette7Section4ElementsCardHeadline : string;
export const ColorPalette7Section4ElementsCardParagraph : string;
export const ColorPalette7Section4NewsletterBackground : string;
export const ColorPalette7Section4NewsletterFormInput : string;
export const ColorPalette7Section4NewsletterLabelPlaceholder : string;
export const ColorPalette7Section4NewsletterFormButton : string;
export const ColorPalette7Section4NewsletterFormButtonText : string;
export const ColorPalette7Section5ElementsBackground : string;
export const ColorPalette7Section5ElementsHeadline : string;
export const ColorPalette7Section5ElementsParagraph : string;
export const ColorPalette7Section5ElementsLinks : string;
