/**
 * Do not edit directly
 * Generated on Sat, 06 May 2023 08:36:34 GMT
 */

export const ColorPalette17Section1ElementsBackground : string;
export const ColorPalette17Section1ElementsHeadline : string;
export const ColorPalette17Section1ElementsParagraph : string;
export const ColorPalette17Section1ElementsButton : string;
export const ColorPalette17Section1ElementsButtonText : string;
export const ColorPalette17Section1IllustrationStroke : string;
export const ColorPalette17Section1IllustrationMain : string;
export const ColorPalette17Section1IllustrationHighlight : string;
export const ColorPalette17Section1IllustrationSecondary : string;
export const ColorPalette17Section1IllustrationTertiary : string;
export const ColorPalette17Section2ElementsBackground : string;
export const ColorPalette17Section2ElementsHeadline : string;
export const ColorPalette17Section2ElementsSubHeadline : string;
export const ColorPalette17Section2ElementsCardBackground : string;
export const ColorPalette17Section2ElementsCardHeading : string;
export const ColorPalette17Section2ElementsCardParagraph : string;
export const ColorPalette17Section2IconsStroke : string;
export const ColorPalette17Section2IconsMain : string;
export const ColorPalette17Section2IconsHighlight : string;
export const ColorPalette17Section2IconsSecondary : string;
export const ColorPalette17Section2IconsTertiary : string;
export const ColorPalette17Section3Background : string;
export const ColorPalette17Section3Headline : string;
export const ColorPalette17Section3Paragraph : string;
export const ColorPalette17Section3CardBackground : string;
export const ColorPalette17Section3CardHeadline : string;
export const ColorPalette17Section3CardParagraph : string;
export const ColorPalette17Section3CardTagBackground : string;
export const ColorPalette17Section3CardTagText : string;
export const ColorPalette17Section3CardHighlight : string;
export const ColorPalette17Section4ElementsBackground : string;
export const ColorPalette17Section4ElementsHeadline : string;
export const ColorPalette17Section4ElementsParagraph : string;
export const ColorPalette17Section4ElementsLink : string;
export const ColorPalette17Section4ElementsCardBackgroud : string;
export const ColorPalette17Section4ElementsCardHeadline : string;
export const ColorPalette17Section4ElementsCardParagraph : string;
export const ColorPalette17Section4NewsletterBackground : string;
export const ColorPalette17Section4NewsletterFormInput : string;
export const ColorPalette17Section4NewsletterLabelPlaceholder : string;
export const ColorPalette17Section4NewsletterFormButton : string;
export const ColorPalette17Section4NewsletterFormButtonText : string;
export const ColorPalette17Section5ElementsBackground : string;
export const ColorPalette17Section5ElementsHeadline : string;
export const ColorPalette17Section5ElementsParagraph : string;
export const ColorPalette17Section5ElementsLinks : string;
