/**
 * Do not edit directly
 * Generated on Sat, 06 May 2023 08:36:34 GMT
 */

export const ColorPalette8Section1ElementsBackground : string;
export const ColorPalette8Section1ElementsHeadline : string;
export const ColorPalette8Section1ElementsParagraph : string;
export const ColorPalette8Section1ElementsButton : string;
export const ColorPalette8Section1ElementsButtonText : string;
export const ColorPalette8Section1IllustrationStroke : string;
export const ColorPalette8Section1IllustrationMain : string;
export const ColorPalette8Section1IllustrationHighlight : string;
export const ColorPalette8Section1IllustrationSecondary : string;
export const ColorPalette8Section1IllustrationTertiary : string;
export const ColorPalette8Section2ElementsBackground : string;
export const ColorPalette8Section2ElementsHeadline : string;
export const ColorPalette8Section2ElementsSubHeadline : string;
export const ColorPalette8Section2ElementsCardBackground : string;
export const ColorPalette8Section2ElementsCardHeading : string;
export const ColorPalette8Section2ElementsCardParagraph : string;
export const ColorPalette8Section2IconsStroke : string;
export const ColorPalette8Section2IconsMain : string;
export const ColorPalette8Section2IconsHighlight : string;
export const ColorPalette8Section2IconsSecondary : string;
export const ColorPalette8Section2IconsTertiary : string;
export const ColorPalette8Section3Background : string;
export const ColorPalette8Section3Headline : string;
export const ColorPalette8Section3Paragraph : string;
export const ColorPalette8Section3CardBackground : string;
export const ColorPalette8Section3CardHeadline : string;
export const ColorPalette8Section3CardParagraph : string;
export const ColorPalette8Section3CardTagBackground : string;
export const ColorPalette8Section3CardTagText : string;
export const ColorPalette8Section3CardHighlight : string;
export const ColorPalette8Section4ElementsBackground : string;
export const ColorPalette8Section4ElementsHeadline : string;
export const ColorPalette8Section4ElementsParagraph : string;
export const ColorPalette8Section4ElementsLink : string;
export const ColorPalette8Section4ElementsCardBackgroud : string;
export const ColorPalette8Section4ElementsCardHeadline : string;
export const ColorPalette8Section4ElementsCardParagraph : string;
export const ColorPalette8Section4NewsletterBackground : string;
export const ColorPalette8Section4NewsletterFormInput : string;
export const ColorPalette8Section4NewsletterLabelPlaceholder : string;
export const ColorPalette8Section4NewsletterFormButton : string;
export const ColorPalette8Section4NewsletterFormButtonText : string;
export const ColorPalette8Section5ElementsBackground : string;
export const ColorPalette8Section5ElementsHeadline : string;
export const ColorPalette8Section5ElementsParagraph : string;
export const ColorPalette8Section5ElementsLinks : string;
