/**
 * Do not edit directly
 * Generated on Sat, 06 May 2023 08:36:34 GMT
 */

export const ColorPalette3Section1ElementsBackground : string;
export const ColorPalette3Section1ElementsHeadline : string;
export const ColorPalette3Section1ElementsParagraph : string;
export const ColorPalette3Section1ElementsButton : string;
export const ColorPalette3Section1ElementsButtonText : string;
export const ColorPalette3Section1IllustrationStroke : string;
export const ColorPalette3Section1IllustrationMain : string;
export const ColorPalette3Section1IllustrationHighlight : string;
export const ColorPalette3Section1IllustrationSecondary : string;
export const ColorPalette3Section1IllustrationTertiary : string;
export const ColorPalette3Section2ElementsBackground : string;
export const ColorPalette3Section2ElementsHeadline : string;
export const ColorPalette3Section2ElementsSubHeadline : string;
export const ColorPalette3Section2ElementsCardBackground : string;
export const ColorPalette3Section2ElementsCardHeading : string;
export const ColorPalette3Section2ElementsCardParagraph : string;
export const ColorPalette3Section2IconsStroke : string;
export const ColorPalette3Section2IconsMain : string;
export const ColorPalette3Section2IconsHighlight : string;
export const ColorPalette3Section2IconsSecondary : string;
export const ColorPalette3Section2IconsTertiary : string;
export const ColorPalette3Section3Background : string;
export const ColorPalette3Section3Headline : string;
export const ColorPalette3Section3Paragraph : string;
export const ColorPalette3Section3CardBackground : string;
export const ColorPalette3Section3CardHeadline : string;
export const ColorPalette3Section3CardParagraph : string;
export const ColorPalette3Section3CardTagBackground : string;
export const ColorPalette3Section3CardTagText : string;
export const ColorPalette3Section3CardHighlight : string;
export const ColorPalette3Section4ElementsBackground : string;
export const ColorPalette3Section4ElementsHeadline : string;
export const ColorPalette3Section4ElementsParagraph : string;
export const ColorPalette3Section4ElementsLink : string;
export const ColorPalette3Section4ElementsCardBackgroud : string;
export const ColorPalette3Section4ElementsCardHeadline : string;
export const ColorPalette3Section4ElementsCardParagraph : string;
export const ColorPalette3Section4NewsletterBackground : string;
export const ColorPalette3Section4NewsletterFormInput : string;
export const ColorPalette3Section4NewsletterLabelPlaceholder : string;
export const ColorPalette3Section4NewsletterFormButton : string;
export const ColorPalette3Section4NewsletterFormButtonText : string;
export const ColorPalette3Section5ElementsBackground : string;
export const ColorPalette3Section5ElementsHeadline : string;
export const ColorPalette3Section5ElementsParagraph : string;
export const ColorPalette3Section5ElementsLinks : string;
