/**
 * Do not edit directly
 * Generated on Sat, 06 May 2023 08:36:34 GMT
 */

export const ColorPalette10Section1ElementsBackground : string;
export const ColorPalette10Section1ElementsHeadline : string;
export const ColorPalette10Section1ElementsParagraph : string;
export const ColorPalette10Section1ElementsButton : string;
export const ColorPalette10Section1ElementsButtonText : string;
export const ColorPalette10Section1IllustrationStroke : string;
export const ColorPalette10Section1IllustrationMain : string;
export const ColorPalette10Section1IllustrationHighlight : string;
export const ColorPalette10Section1IllustrationSecondary : string;
export const ColorPalette10Section1IllustrationTertiary : string;
export const ColorPalette10Section2ElementsBackground : string;
export const ColorPalette10Section2ElementsHeadline : string;
export const ColorPalette10Section2ElementsSubHeadline : string;
export const ColorPalette10Section2ElementsCardBackground : string;
export const ColorPalette10Section2ElementsCardHeading : string;
export const ColorPalette10Section2ElementsCardParagraph : string;
export const ColorPalette10Section2IconsStroke : string;
export const ColorPalette10Section2IconsMain : string;
export const ColorPalette10Section2IconsHighlight : string;
export const ColorPalette10Section2IconsSecondary : string;
export const ColorPalette10Section2IconsTertiary : string;
export const ColorPalette10Section3Background : string;
export const ColorPalette10Section3Headline : string;
export const ColorPalette10Section3Paragraph : string;
export const ColorPalette10Section3CardBackground : string;
export const ColorPalette10Section3CardHeadline : string;
export const ColorPalette10Section3CardParagraph : string;
export const ColorPalette10Section3CardTagBackground : string;
export const ColorPalette10Section3CardTagText : string;
export const ColorPalette10Section3CardHighlight : string;
export const ColorPalette10Section4ElementsBackground : string;
export const ColorPalette10Section4ElementsHeadline : string;
export const ColorPalette10Section4ElementsParagraph : string;
export const ColorPalette10Section4ElementsLink : string;
export const ColorPalette10Section4ElementsCardBackgroud : string;
export const ColorPalette10Section4ElementsCardHeadline : string;
export const ColorPalette10Section4ElementsCardParagraph : string;
export const ColorPalette10Section4NewsletterBackground : string;
export const ColorPalette10Section4NewsletterFormInput : string;
export const ColorPalette10Section4NewsletterLabelPlaceholder : string;
export const ColorPalette10Section4NewsletterFormButton : string;
export const ColorPalette10Section4NewsletterFormButtonText : string;
export const ColorPalette10Section5ElementsBackground : string;
export const ColorPalette10Section5ElementsHeadline : string;
export const ColorPalette10Section5ElementsParagraph : string;
export const ColorPalette10Section5ElementsLinks : string;
