/**
 * Do not edit directly
 * Generated on Sat, 06 May 2023 08:36:34 GMT
 */

export const ColorPalette15Section1ElementsBackground : string;
export const ColorPalette15Section1ElementsHeadline : string;
export const ColorPalette15Section1ElementsParagraph : string;
export const ColorPalette15Section1ElementsButton : string;
export const ColorPalette15Section1ElementsButtonText : string;
export const ColorPalette15Section1IllustrationStroke : string;
export const ColorPalette15Section1IllustrationMain : string;
export const ColorPalette15Section1IllustrationHighlight : string;
export const ColorPalette15Section1IllustrationSecondary : string;
export const ColorPalette15Section1IllustrationTertiary : string;
export const ColorPalette15Section2ElementsBackground : string;
export const ColorPalette15Section2ElementsHeadline : string;
export const ColorPalette15Section2ElementsSubHeadline : string;
export const ColorPalette15Section2ElementsCardBackground : string;
export const ColorPalette15Section2ElementsCardHeading : string;
export const ColorPalette15Section2ElementsCardParagraph : string;
export const ColorPalette15Section2IconsStroke : string;
export const ColorPalette15Section2IconsMain : string;
export const ColorPalette15Section2IconsHighlight : string;
export const ColorPalette15Section2IconsSecondary : string;
export const ColorPalette15Section2IconsTertiary : string;
export const ColorPalette15Section3Background : string;
export const ColorPalette15Section3Headline : string;
export const ColorPalette15Section3Paragraph : string;
export const ColorPalette15Section3CardBackground : string;
export const ColorPalette15Section3CardHeadline : string;
export const ColorPalette15Section3CardParagraph : string;
export const ColorPalette15Section3CardTagBackground : string;
export const ColorPalette15Section3CardTagText : string;
export const ColorPalette15Section3CardHighlight : string;
export const ColorPalette15Section4ElementsBackground : string;
export const ColorPalette15Section4ElementsHeadline : string;
export const ColorPalette15Section4ElementsParagraph : string;
export const ColorPalette15Section4ElementsLink : string;
export const ColorPalette15Section4ElementsCardBackgroud : string;
export const ColorPalette15Section4ElementsCardHeadline : string;
export const ColorPalette15Section4ElementsCardParagraph : string;
export const ColorPalette15Section4NewsletterBackground : string;
export const ColorPalette15Section4NewsletterFormInput : string;
export const ColorPalette15Section4NewsletterLabelPlaceholder : string;
export const ColorPalette15Section4NewsletterFormButton : string;
export const ColorPalette15Section4NewsletterFormButtonText : string;
export const ColorPalette15Section5ElementsBackground : string;
export const ColorPalette15Section5ElementsHeadline : string;
export const ColorPalette15Section5ElementsParagraph : string;
export const ColorPalette15Section5ElementsLinks : string;
