/**
 * Do not edit directly
 * Generated on Sat, 06 May 2023 08:36:34 GMT
 */

export const ColorPalette16Section1ElementsBackground : string;
export const ColorPalette16Section1ElementsHeadline : string;
export const ColorPalette16Section1ElementsParagraph : string;
export const ColorPalette16Section1ElementsButton : string;
export const ColorPalette16Section1ElementsButtonText : string;
export const ColorPalette16Section1IllustrationStroke : string;
export const ColorPalette16Section1IllustrationMain : string;
export const ColorPalette16Section1IllustrationHighlight : string;
export const ColorPalette16Section1IllustrationSecondary : string;
export const ColorPalette16Section1IllustrationTertiary : string;
export const ColorPalette16Section2ElementsBackground : string;
export const ColorPalette16Section2ElementsHeadline : string;
export const ColorPalette16Section2ElementsSubHeadline : string;
export const ColorPalette16Section2ElementsCardBackground : string;
export const ColorPalette16Section2ElementsCardHeading : string;
export const ColorPalette16Section2ElementsCardParagraph : string;
export const ColorPalette16Section2IconsStroke : string;
export const ColorPalette16Section2IconsMain : string;
export const ColorPalette16Section2IconsHighlight : string;
export const ColorPalette16Section2IconsSecondary : string;
export const ColorPalette16Section2IconsTertiary : string;
export const ColorPalette16Section3Background : string;
export const ColorPalette16Section3Headline : string;
export const ColorPalette16Section3Paragraph : string;
export const ColorPalette16Section3CardBackground : string;
export const ColorPalette16Section3CardHeadline : string;
export const ColorPalette16Section3CardParagraph : string;
export const ColorPalette16Section3CardTagBackground : string;
export const ColorPalette16Section3CardTagText : string;
export const ColorPalette16Section3CardHighlight : string;
export const ColorPalette16Section4ElementsBackground : string;
export const ColorPalette16Section4ElementsHeadline : string;
export const ColorPalette16Section4ElementsParagraph : string;
export const ColorPalette16Section4ElementsLink : string;
export const ColorPalette16Section4ElementsCardBackgroud : string;
export const ColorPalette16Section4ElementsCardHeadline : string;
export const ColorPalette16Section4ElementsCardParagraph : string;
export const ColorPalette16Section4NewsletterBackground : string;
export const ColorPalette16Section4NewsletterFormInput : string;
export const ColorPalette16Section4NewsletterLabelPlaceholder : string;
export const ColorPalette16Section4NewsletterFormButton : string;
export const ColorPalette16Section4NewsletterFormButtonText : string;
export const ColorPalette16Section5ElementsBackground : string;
export const ColorPalette16Section5ElementsHeadline : string;
export const ColorPalette16Section5ElementsParagraph : string;
export const ColorPalette16Section5ElementsLinks : string;
