/**
 * Do not edit directly
 * Generated on Sat, 06 May 2023 08:36:34 GMT
 */

export const ColorPalette2Section1ElementsBackground : string;
export const ColorPalette2Section1ElementsHeadline : string;
export const ColorPalette2Section1ElementsParagraph : string;
export const ColorPalette2Section1ElementsButton : string;
export const ColorPalette2Section1ElementsButtonText : string;
export const ColorPalette2Section1IllustrationStroke : string;
export const ColorPalette2Section1IllustrationMain : string;
export const ColorPalette2Section1IllustrationHighlight : string;
export const ColorPalette2Section1IllustrationSecondary : string;
export const ColorPalette2Section1IllustrationTertiary : string;
export const ColorPalette2Section2ElementsBackground : string;
export const ColorPalette2Section2ElementsHeadline : string;
export const ColorPalette2Section2ElementsSubHeadline : string;
export const ColorPalette2Section2ElementsCardBackground : string;
export const ColorPalette2Section2ElementsCardHeading : string;
export const ColorPalette2Section2ElementsCardParagraph : string;
export const ColorPalette2Section2IconsStroke : string;
export const ColorPalette2Section2IconsMain : string;
export const ColorPalette2Section2IconsHighlight : string;
export const ColorPalette2Section2IconsSecondary : string;
export const ColorPalette2Section2IconsTertiary : string;
export const ColorPalette2Section3Background : string;
export const ColorPalette2Section3Headline : string;
export const ColorPalette2Section3Paragraph : string;
export const ColorPalette2Section3CardBackground : string;
export const ColorPalette2Section3CardHeadline : string;
export const ColorPalette2Section3CardParagraph : string;
export const ColorPalette2Section3CardTagBackground : string;
export const ColorPalette2Section3CardTagText : string;
export const ColorPalette2Section3CardHighlight : string;
export const ColorPalette2Section4ElementsBackground : string;
export const ColorPalette2Section4ElementsHeadline : string;
export const ColorPalette2Section4ElementsParagraph : string;
export const ColorPalette2Section4ElementsLink : string;
export const ColorPalette2Section4ElementsCardBackgroud : string;
export const ColorPalette2Section4ElementsCardHeadline : string;
export const ColorPalette2Section4ElementsCardParagraph : string;
export const ColorPalette2Section4NewsletterBackground : string;
export const ColorPalette2Section4NewsletterFormInput : string;
export const ColorPalette2Section4NewsletterLabelPlaceholder : string;
export const ColorPalette2Section4NewsletterFormButton : string;
export const ColorPalette2Section4NewsletterFormButtonText : string;
export const ColorPalette2Section5ElementsBackground : string;
export const ColorPalette2Section5ElementsHeadline : string;
export const ColorPalette2Section5ElementsParagraph : string;
export const ColorPalette2Section5ElementsLinks : string;
