/**
 * Do not edit directly
 * Generated on Sat, 06 May 2023 08:36:34 GMT
 */

export const ColorPalette12Section1ElementsBackground : string;
export const ColorPalette12Section1ElementsHeadline : string;
export const ColorPalette12Section1ElementsParagraph : string;
export const ColorPalette12Section1ElementsButton : string;
export const ColorPalette12Section1ElementsButtonText : string;
export const ColorPalette12Section1IllustrationStroke : string;
export const ColorPalette12Section1IllustrationMain : string;
export const ColorPalette12Section1IllustrationHighlight : string;
export const ColorPalette12Section1IllustrationSecondary : string;
export const ColorPalette12Section1IllustrationTertiary : string;
export const ColorPalette12Section2ElementsBackground : string;
export const ColorPalette12Section2ElementsHeadline : string;
export const ColorPalette12Section2ElementsSubHeadline : string;
export const ColorPalette12Section2ElementsCardBackground : string;
export const ColorPalette12Section2ElementsCardHeading : string;
export const ColorPalette12Section2ElementsCardParagraph : string;
export const ColorPalette12Section2IconsStroke : string;
export const ColorPalette12Section2IconsMain : string;
export const ColorPalette12Section2IconsHighlight : string;
export const ColorPalette12Section2IconsSecondary : string;
export const ColorPalette12Section2IconsTertiary : string;
export const ColorPalette12Section3Background : string;
export const ColorPalette12Section3Headline : string;
export const ColorPalette12Section3Paragraph : string;
export const ColorPalette12Section3CardBackground : string;
export const ColorPalette12Section3CardHeadline : string;
export const ColorPalette12Section3CardParagraph : string;
export const ColorPalette12Section3CardTagBackground : string;
export const ColorPalette12Section3CardTagText : string;
export const ColorPalette12Section3CardHighlight : string;
export const ColorPalette12Section4ElementsBackground : string;
export const ColorPalette12Section4ElementsHeadline : string;
export const ColorPalette12Section4ElementsParagraph : string;
export const ColorPalette12Section4ElementsLink : string;
export const ColorPalette12Section4ElementsCardBackgroud : string;
export const ColorPalette12Section4ElementsCardHeadline : string;
export const ColorPalette12Section4ElementsCardParagraph : string;
export const ColorPalette12Section4NewsletterBackground : string;
export const ColorPalette12Section4NewsletterFormInput : string;
export const ColorPalette12Section4NewsletterLabelPlaceholder : string;
export const ColorPalette12Section4NewsletterFormButton : string;
export const ColorPalette12Section4NewsletterFormButtonText : string;
export const ColorPalette12Section5ElementsBackground : string;
export const ColorPalette12Section5ElementsHeadline : string;
export const ColorPalette12Section5ElementsParagraph : string;
export const ColorPalette12Section5ElementsLinks : string;
