/**
 * Do not edit directly
 * Generated on Sat, 06 May 2023 08:36:34 GMT
 */

export const ColorPalette9Section1ElementsBackground : string;
export const ColorPalette9Section1ElementsHeadline : string;
export const ColorPalette9Section1ElementsParagraph : string;
export const ColorPalette9Section1ElementsButton : string;
export const ColorPalette9Section1ElementsButtonText : string;
export const ColorPalette9Section1IllustrationStroke : string;
export const ColorPalette9Section1IllustrationMain : string;
export const ColorPalette9Section1IllustrationHighlight : string;
export const ColorPalette9Section1IllustrationSecondary : string;
export const ColorPalette9Section1IllustrationTertiary : string;
export const ColorPalette9Section2ElementsBackground : string;
export const ColorPalette9Section2ElementsHeadline : string;
export const ColorPalette9Section2ElementsSubHeadline : string;
export const ColorPalette9Section2ElementsCardBackground : string;
export const ColorPalette9Section2ElementsCardHeading : string;
export const ColorPalette9Section2ElementsCardParagraph : string;
export const ColorPalette9Section2IconsStroke : string;
export const ColorPalette9Section2IconsMain : string;
export const ColorPalette9Section2IconsHighlight : string;
export const ColorPalette9Section2IconsSecondary : string;
export const ColorPalette9Section2IconsTertiary : string;
export const ColorPalette9Section3Background : string;
export const ColorPalette9Section3Headline : string;
export const ColorPalette9Section3Paragraph : string;
export const ColorPalette9Section3CardBackground : string;
export const ColorPalette9Section3CardHeadline : string;
export const ColorPalette9Section3CardParagraph : string;
export const ColorPalette9Section3CardTagBackground : string;
export const ColorPalette9Section3CardTagText : string;
export const ColorPalette9Section3CardHighlight : string;
export const ColorPalette9Section4ElementsBackground : string;
export const ColorPalette9Section4ElementsHeadline : string;
export const ColorPalette9Section4ElementsParagraph : string;
export const ColorPalette9Section4ElementsLink : string;
export const ColorPalette9Section4ElementsCardBackgroud : string;
export const ColorPalette9Section4ElementsCardHeadline : string;
export const ColorPalette9Section4ElementsCardParagraph : string;
export const ColorPalette9Section4NewsletterBackground : string;
export const ColorPalette9Section4NewsletterFormInput : string;
export const ColorPalette9Section4NewsletterLabelPlaceholder : string;
export const ColorPalette9Section4NewsletterFormButton : string;
export const ColorPalette9Section4NewsletterFormButtonText : string;
export const ColorPalette9Section5ElementsBackground : string;
export const ColorPalette9Section5ElementsHeadline : string;
export const ColorPalette9Section5ElementsParagraph : string;
export const ColorPalette9Section5ElementsLinks : string;
