/**
 * Do not edit directly
 * Generated on Sat, 06 May 2023 08:36:34 GMT
 */

export const ColorPalette4Section1ElementsBackground : string;
export const ColorPalette4Section1ElementsHeadline : string;
export const ColorPalette4Section1ElementsParagraph : string;
export const ColorPalette4Section1ElementsButton : string;
export const ColorPalette4Section1ElementsButtonText : string;
export const ColorPalette4Section1IllustrationStroke : string;
export const ColorPalette4Section1IllustrationMain : string;
export const ColorPalette4Section1IllustrationHighlight : string;
export const ColorPalette4Section1IllustrationSecondary : string;
export const ColorPalette4Section1IllustrationTertiary : string;
export const ColorPalette4Section2ElementsBackground : string;
export const ColorPalette4Section2ElementsHeadline : string;
export const ColorPalette4Section2ElementsSubHeadline : string;
export const ColorPalette4Section2ElementsCardBackground : string;
export const ColorPalette4Section2ElementsCardHeading : string;
export const ColorPalette4Section2ElementsCardParagraph : string;
export const ColorPalette4Section2IconsStroke : string;
export const ColorPalette4Section2IconsMain : string;
export const ColorPalette4Section2IconsHighlight : string;
export const ColorPalette4Section2IconsSecondary : string;
export const ColorPalette4Section2IconsTertiary : string;
export const ColorPalette4Section3Background : string;
export const ColorPalette4Section3Headline : string;
export const ColorPalette4Section3Paragraph : string;
export const ColorPalette4Section3CardBackground : string;
export const ColorPalette4Section3CardHeadline : string;
export const ColorPalette4Section3CardParagraph : string;
export const ColorPalette4Section3CardTagBackground : string;
export const ColorPalette4Section3CardTagText : string;
export const ColorPalette4Section3CardHighlight : string;
export const ColorPalette4Section4ElementsBackground : string;
export const ColorPalette4Section4ElementsHeadline : string;
export const ColorPalette4Section4ElementsParagraph : string;
export const ColorPalette4Section4ElementsLink : string;
export const ColorPalette4Section4ElementsCardBackgroud : string;
export const ColorPalette4Section4ElementsCardHeadline : string;
export const ColorPalette4Section4ElementsCardParagraph : string;
export const ColorPalette4Section4NewsletterBackground : string;
export const ColorPalette4Section4NewsletterFormInput : string;
export const ColorPalette4Section4NewsletterLabelPlaceholder : string;
export const ColorPalette4Section4NewsletterFormButton : string;
export const ColorPalette4Section4NewsletterFormButtonText : string;
export const ColorPalette4Section5ElementsBackground : string;
export const ColorPalette4Section5ElementsHeadline : string;
export const ColorPalette4Section5ElementsParagraph : string;
export const ColorPalette4Section5ElementsLinks : string;
