/**
 * Do not edit directly
 * Generated on Sat, 06 May 2023 08:36:34 GMT
 */

export const ColorPalette5Section1ElementsBackground : string;
export const ColorPalette5Section1ElementsHeadline : string;
export const ColorPalette5Section1ElementsParagraph : string;
export const ColorPalette5Section1ElementsButton : string;
export const ColorPalette5Section1ElementsButtonText : string;
export const ColorPalette5Section1IllustrationStroke : string;
export const ColorPalette5Section1IllustrationMain : string;
export const ColorPalette5Section1IllustrationHighlight : string;
export const ColorPalette5Section1IllustrationSecondary : string;
export const ColorPalette5Section1IllustrationTertiary : string;
export const ColorPalette5Section2ElementsBackground : string;
export const ColorPalette5Section2ElementsHeadline : string;
export const ColorPalette5Section2ElementsSubHeadline : string;
export const ColorPalette5Section2ElementsCardBackground : string;
export const ColorPalette5Section2ElementsCardHeading : string;
export const ColorPalette5Section2ElementsCardParagraph : string;
export const ColorPalette5Section2IconsStroke : string;
export const ColorPalette5Section2IconsMain : string;
export const ColorPalette5Section2IconsHighlight : string;
export const ColorPalette5Section2IconsSecondary : string;
export const ColorPalette5Section2IconsTertiary : string;
export const ColorPalette5Section3Background : string;
export const ColorPalette5Section3Headline : string;
export const ColorPalette5Section3Paragraph : string;
export const ColorPalette5Section3CardBackground : string;
export const ColorPalette5Section3CardHeadline : string;
export const ColorPalette5Section3CardParagraph : string;
export const ColorPalette5Section3CardTagBackground : string;
export const ColorPalette5Section3CardTagText : string;
export const ColorPalette5Section3CardHighlight : string;
export const ColorPalette5Section4ElementsBackground : string;
export const ColorPalette5Section4ElementsHeadline : string;
export const ColorPalette5Section4ElementsParagraph : string;
export const ColorPalette5Section4ElementsLink : string;
export const ColorPalette5Section4ElementsCardBackgroud : string;
export const ColorPalette5Section4ElementsCardHeadline : string;
export const ColorPalette5Section4ElementsCardParagraph : string;
export const ColorPalette5Section4NewsletterBackground : string;
export const ColorPalette5Section4NewsletterFormInput : string;
export const ColorPalette5Section4NewsletterLabelPlaceholder : string;
export const ColorPalette5Section4NewsletterFormButton : string;
export const ColorPalette5Section4NewsletterFormButtonText : string;
export const ColorPalette5Section5ElementsBackground : string;
export const ColorPalette5Section5ElementsHeadline : string;
export const ColorPalette5Section5ElementsParagraph : string;
export const ColorPalette5Section5ElementsLinks : string;
