/**
 * Do not edit directly
 * Generated on Sat, 06 May 2023 08:36:34 GMT
 */

export const ColorPalette11Section1ElementsBackground : string;
export const ColorPalette11Section1ElementsHeadline : string;
export const ColorPalette11Section1ElementsParagraph : string;
export const ColorPalette11Section1ElementsButton : string;
export const ColorPalette11Section1ElementsButtonText : string;
export const ColorPalette11Section1IllustrationStroke : string;
export const ColorPalette11Section1IllustrationMain : string;
export const ColorPalette11Section1IllustrationHighlight : string;
export const ColorPalette11Section1IllustrationSecondary : string;
export const ColorPalette11Section1IllustrationTertiary : string;
export const ColorPalette11Section2ElementsBackground : string;
export const ColorPalette11Section2ElementsHeadline : string;
export const ColorPalette11Section2ElementsSubHeadline : string;
export const ColorPalette11Section2ElementsCardBackground : string;
export const ColorPalette11Section2ElementsCardHeading : string;
export const ColorPalette11Section2ElementsCardParagraph : string;
export const ColorPalette11Section2IconsStroke : string;
export const ColorPalette11Section2IconsMain : string;
export const ColorPalette11Section2IconsHighlight : string;
export const ColorPalette11Section2IconsSecondary : string;
export const ColorPalette11Section2IconsTertiary : string;
export const ColorPalette11Section3Background : string;
export const ColorPalette11Section3Headline : string;
export const ColorPalette11Section3Paragraph : string;
export const ColorPalette11Section3CardBackground : string;
export const ColorPalette11Section3CardHeadline : string;
export const ColorPalette11Section3CardParagraph : string;
export const ColorPalette11Section3CardTagBackground : string;
export const ColorPalette11Section3CardTagText : string;
export const ColorPalette11Section3CardHighlight : string;
export const ColorPalette11Section4ElementsBackground : string;
export const ColorPalette11Section4ElementsHeadline : string;
export const ColorPalette11Section4ElementsParagraph : string;
export const ColorPalette11Section4ElementsLink : string;
export const ColorPalette11Section4ElementsCardBackgroud : string;
export const ColorPalette11Section4ElementsCardHeadline : string;
export const ColorPalette11Section4ElementsCardParagraph : string;
export const ColorPalette11Section4NewsletterBackground : string;
export const ColorPalette11Section4NewsletterFormInput : string;
export const ColorPalette11Section4NewsletterLabelPlaceholder : string;
export const ColorPalette11Section4NewsletterFormButton : string;
export const ColorPalette11Section4NewsletterFormButtonText : string;
export const ColorPalette11Section5ElementsBackground : string;
export const ColorPalette11Section5ElementsHeadline : string;
export const ColorPalette11Section5ElementsParagraph : string;
export const ColorPalette11Section5ElementsLinks : string;
