/**
 * Do not edit directly
 * Generated on Sat, 06 May 2023 08:36:34 GMT
 */

export const ColorPalette14Section1ElementsBackground : string;
export const ColorPalette14Section1ElementsHeadline : string;
export const ColorPalette14Section1ElementsParagraph : string;
export const ColorPalette14Section1ElementsButton : string;
export const ColorPalette14Section1ElementsButtonText : string;
export const ColorPalette14Section1IllustrationStroke : string;
export const ColorPalette14Section1IllustrationMain : string;
export const ColorPalette14Section1IllustrationHighlight : string;
export const ColorPalette14Section1IllustrationSecondary : string;
export const ColorPalette14Section1IllustrationTertiary : string;
export const ColorPalette14Section2ElementsBackground : string;
export const ColorPalette14Section2ElementsHeadline : string;
export const ColorPalette14Section2ElementsSubHeadline : string;
export const ColorPalette14Section2ElementsCardBackground : string;
export const ColorPalette14Section2ElementsCardHeading : string;
export const ColorPalette14Section2ElementsCardParagraph : string;
export const ColorPalette14Section2IconsStroke : string;
export const ColorPalette14Section2IconsMain : string;
export const ColorPalette14Section2IconsHighlight : string;
export const ColorPalette14Section2IconsSecondary : string;
export const ColorPalette14Section2IconsTertiary : string;
export const ColorPalette14Section3Background : string;
export const ColorPalette14Section3Headline : string;
export const ColorPalette14Section3Paragraph : string;
export const ColorPalette14Section3CardBackground : string;
export const ColorPalette14Section3CardHeadline : string;
export const ColorPalette14Section3CardParagraph : string;
export const ColorPalette14Section3CardTagBackground : string;
export const ColorPalette14Section3CardTagText : string;
export const ColorPalette14Section3CardHighlight : string;
export const ColorPalette14Section4ElementsBackground : string;
export const ColorPalette14Section4ElementsHeadline : string;
export const ColorPalette14Section4ElementsParagraph : string;
export const ColorPalette14Section4ElementsLink : string;
export const ColorPalette14Section4ElementsCardBackgroud : string;
export const ColorPalette14Section4ElementsCardHeadline : string;
export const ColorPalette14Section4ElementsCardParagraph : string;
export const ColorPalette14Section4NewsletterBackground : string;
export const ColorPalette14Section4NewsletterFormInput : string;
export const ColorPalette14Section4NewsletterLabelPlaceholder : string;
export const ColorPalette14Section4NewsletterFormButton : string;
export const ColorPalette14Section4NewsletterFormButtonText : string;
export const ColorPalette14Section5ElementsBackground : string;
export const ColorPalette14Section5ElementsHeadline : string;
export const ColorPalette14Section5ElementsParagraph : string;
export const ColorPalette14Section5ElementsLinks : string;
