/**
 * Do not edit directly
 * Generated on Sat, 06 May 2023 08:36:34 GMT
 */

export const ColorPalette13Section1ElementsBackground : string;
export const ColorPalette13Section1ElementsHeadline : string;
export const ColorPalette13Section1ElementsParagraph : string;
export const ColorPalette13Section1ElementsButton : string;
export const ColorPalette13Section1ElementsButtonText : string;
export const ColorPalette13Section1IllustrationStroke : string;
export const ColorPalette13Section1IllustrationMain : string;
export const ColorPalette13Section1IllustrationHighlight : string;
export const ColorPalette13Section1IllustrationSecondary : string;
export const ColorPalette13Section1IllustrationTertiary : string;
export const ColorPalette13Section2ElementsBackground : string;
export const ColorPalette13Section2ElementsHeadline : string;
export const ColorPalette13Section2ElementsSubHeadline : string;
export const ColorPalette13Section2ElementsCardBackground : string;
export const ColorPalette13Section2ElementsCardHeading : string;
export const ColorPalette13Section2ElementsCardParagraph : string;
export const ColorPalette13Section2IconsStroke : string;
export const ColorPalette13Section2IconsMain : string;
export const ColorPalette13Section2IconsHighlight : string;
export const ColorPalette13Section2IconsSecondary : string;
export const ColorPalette13Section2IconsTertiary : string;
export const ColorPalette13Section3Background : string;
export const ColorPalette13Section3Headline : string;
export const ColorPalette13Section3Paragraph : string;
export const ColorPalette13Section3CardBackground : string;
export const ColorPalette13Section3CardHeadline : string;
export const ColorPalette13Section3CardParagraph : string;
export const ColorPalette13Section3CardTagBackground : string;
export const ColorPalette13Section3CardTagText : string;
export const ColorPalette13Section3CardHighlight : string;
export const ColorPalette13Section4ElementsBackground : string;
export const ColorPalette13Section4ElementsHeadline : string;
export const ColorPalette13Section4ElementsParagraph : string;
export const ColorPalette13Section4ElementsLink : string;
export const ColorPalette13Section4ElementsCardBackgroud : string;
export const ColorPalette13Section4ElementsCardHeadline : string;
export const ColorPalette13Section4ElementsCardParagraph : string;
export const ColorPalette13Section4NewsletterBackground : string;
export const ColorPalette13Section4NewsletterFormInput : string;
export const ColorPalette13Section4NewsletterLabelPlaceholder : string;
export const ColorPalette13Section4NewsletterFormButton : string;
export const ColorPalette13Section4NewsletterFormButtonText : string;
export const ColorPalette13Section5ElementsBackground : string;
export const ColorPalette13Section5ElementsHeadline : string;
export const ColorPalette13Section5ElementsParagraph : string;
export const ColorPalette13Section5ElementsLinks : string;
