-- Your SQL goes here
CREATE TABLE IF NOT EXISTS folders (
  id INTEGER NOT NULL PRIMARY KEY,
  uuid VARCHAR NOT NULL UNIQUE,
  name VARCHAR NOT NULL,
  create_date DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
  update_date DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP
);

CREATE TABLE IF NOT EXISTS folder_channel_relations (
  id INTEGER NOT NULL PRIMARY KEY,
  folder_uuid VARCHAR NOT NULL,
  channel_uuid VARCHAR NOT NUll,
  create_date DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
  UNIQUE("folder_uuid", "channel_uuid")
);

ALTER TABLE channels ADD COLUMN create_date DATETIME NOT NULL DEFAULT "";
ALTER TABLE channels ADD COLUMN update_date DATETIME NOT NULL DEFAULT "";
