export const SYNC_UNREAD_WHEN_APP_START = 'SYNC_UNREAD_WHEN_APP_START';
export const FINISH_INITIAL_SYNC = 'FINISH_INITIAL_SYNC';
export const MANUAL_SYNC_UNREAD = 'MANUAL_SYNC_UNREAD';
export const MANUAL_SYNC_UNREAD_WITH_CHANNEL_ID =
  'MANUAL_SYNC_UNREAD_WITH_CHANNEL_ID';

export const MARK_ARTICLE_READ = 'MARK_ARTICLE_READ';
export const MARK_ARTICLE_READ_BY_CHANNEL = 'MARK_ARTICLE_READ_BY_CHANNEL';

export const FINISH_MANUAL_SYNC_UNREAD = 'FINISH_MANUAL_SYNC_UNREAD';
export const UPDATE_WINDOW_ID = 'UPDATE_WINDOW_ID';

/**
 * 导出
 */
export const EXPORT_OPML = 'EXPORT_OPML';
export const FINISH_EXPORT_OPML = 'FINISH_EXPORT_OPML';

export const IMPORT_OPML = 'IMPORT_OPML';
export const FINISH_IMPORT_OPML = 'FINISH_IMPORT_OPML';

export const SUBSCRIBE = 'SUBSCRIBE';

export const PROXY_GET_CHANNEL_LIST = 'PROXY_GET_CHANNEL_LIST';
export const PROXY_GET_ARTICLE_LSIT = 'PROXY_GET_ARTICLE_LSIT';
export const PROXY_GET_ARTICLE_LIST_IN_CHANNEL =
  'PROXY_GET_ARTICLE_LIST_IN_CHANNEL';
export const PROXY_GET_UNREAD_TOTAL = 'PROXY_GET_UNREAD_TOTAL';

/*
 * 同步文章
 */
export const PROXY_SYNC_ARTICLE_BY_CHANNEL = 'PROXY_SYNC_ARTICLE_BY_CHANNEL';

// 取消订阅
export const PROXY_CANCEL_SUBSCRIBE = 'PROXY_CANCEL_SUBSCRIBE';
