name: 'Update latest version'
on:
  push:
    branches:
      - release
env:
  TAURI_PRIVATE_KEY: ${{ secrets.TAURI_PRIVATE_KEY }}
  TAURI_KEY_PASSWORD: ${{ secrets.TAURI_KEY_PASSWORD }}

jobs:
  update_json:
    runs-on: ubuntu-latest
    steps:
      - name: Set Node.js Env
        uses: actions/setup-node@v3
        with:
          node-version: 'lts/*'
      - name: Create file
        working-directory: ./
        run: |
          echo `pwd`
          node ./scripts/updater.mjs
